# Generated by Django 2.2.10 on 2020-02-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200228_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='choices',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.ManyToManyField(related_name='answer', to='questions.Choice'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice',
            field=models.ManyToManyField(related_name='choice', to='questions.Choice'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
