# Generated by Django 2.2.5 on 2020-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20200310_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='createdDate',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
