# Generated by Django 2.2.5 on 2020-03-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20200310_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='createdDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
