# Generated by Django 2.2.5 on 2020-03-10 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20200310_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='createdDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
