# Generated by Django 2.2.5 on 2020-03-10 07:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20200310_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='createdDate',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
