# Generated by Django 2.2.5 on 2020-03-10 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_auto_20200310_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.ManyToManyField(blank=True, null=True, related_name='answer', to='questions.Choice'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.Area'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.Category'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choice',
            field=models.ManyToManyField(blank=True, null=True, related_name='choice', to='questions.Choice'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='difficulty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.Difficulty'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.Process'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questions.Skill'),
        ),
    ]
