# Generated by Django 2.2.10 on 2020-02-26 01:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(default='None', max_length=500)),
                ('timeDuration', models.DateTimeField(blank=True, null=True)),
                ('createdDate', models.DateField(default=datetime.datetime.now)),
                ('comments', models.CharField(default='None', max_length=500)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
