# Generated by Django 2.2.5 on 2020-03-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='timeDuration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
