# Generated by Django 2.2.5 on 2020-03-02 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200302_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='timeDuration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
