# Generated by Django 2.2.5 on 2020-03-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20200302_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='timeDuration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
