# Generated by Django 2.2.5 on 2020-03-03 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20200303_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='timeDuration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600), null=True),
        ),
    ]
