# Generated by Django 2.2.5 on 2020-03-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20200303_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='timeDuration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
