# Generated by Django 2.2.5 on 2020-03-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_applicantexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantexam',
            name='exam',
            field=models.ManyToManyField(related_name='applicant_Exam', to='exam.Exams'),
        ),
    ]
