# Generated by Django 2.2.10 on 2020-03-16 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20200310_1522'),
        ('exam', '0013_auto_20200306_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exams',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='exams',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='questions.Questions'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
