# Generated by Django 2.2.10 on 2020-03-16 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employer.Employer', verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='department',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employer.Employer', verbose_name='Created By'),
        ),
    ]
